var command_reference =
[
    [ "Animation commands", "animation_commands.html", [
      [ "Play Anim State", "animation_commands.html#PlayAnimState", null ],
      [ "Reset Anim Trigger", "animation_commands.html#ResetAnimTrigger", null ],
      [ "Set Anim Bool", "animation_commands.html#SetAnimBool", null ],
      [ "Set Anim Float", "animation_commands.html#SetAnimFloat", null ],
      [ "Set Anim Integer", "animation_commands.html#SetAnimInteger", null ],
      [ "Set Anim Trigger", "animation_commands.html#SetAnimTrigger", null ]
    ] ],
    [ "Audio commands", "audio_commands.html", [
      [ "Control Audio", "audio_commands.html#ControlAudio", null ],
      [ "Play Music", "audio_commands.html#PlayMusic", null ],
      [ "Play Sound", "audio_commands.html#PlaySound", null ],
      [ "Play Usfxr Sound", "audio_commands.html#PlayUsfxrSound", null ],
      [ "Set Audio Pitch", "audio_commands.html#SetAudioPitch", null ],
      [ "Set Audio Volume", "audio_commands.html#SetAudioVolume", null ],
      [ "Stop Music", "audio_commands.html#StopMusic", null ]
    ] ],
    [ "Camera commands", "camera_commands.html", [
      [ "Fade Screen", "camera_commands.html#FadeScreen", null ],
      [ "Fade To View", "camera_commands.html#FadeToView", null ],
      [ "Fullscreen", "camera_commands.html#Fullscreen", null ],
      [ "Move To View", "camera_commands.html#MoveToView", null ],
      [ "Shake Camera", "camera_commands.html#ShakeCamera", null ],
      [ "Start Swipe", "camera_commands.html#StartSwipe", null ],
      [ "Stop Swipe", "camera_commands.html#StopSwipe", null ]
    ] ],
    [ "Flow commands", "flow_commands.html", [
      [ "Break", "flow_commands.html#Break", null ],
      [ "Call", "flow_commands.html#Call", null ],
      [ "Else", "flow_commands.html#Else", null ],
      [ "Else If", "flow_commands.html#ElseIf", null ],
      [ "End", "flow_commands.html#End", null ],
      [ "If", "flow_commands.html#If", null ],
      [ "Jump", "flow_commands.html#Jump", null ],
      [ "Label", "flow_commands.html#Label", null ],
      [ "Load Scene", "flow_commands.html#LoadScene", null ],
      [ "Lua Else If", "flow_commands.html#LuaElseIf", null ],
      [ "Lua If", "flow_commands.html#LuaIf", null ],
      [ "Quit", "flow_commands.html#Quit", null ],
      [ "Save Point", "flow_commands.html#SavePoint", null ],
      [ "Send Message", "flow_commands.html#SendMessage", null ],
      [ "Stop", "flow_commands.html#Stop", null ],
      [ "Stop Block", "flow_commands.html#StopBlock", null ],
      [ "Stop Flowchart", "flow_commands.html#StopFlowchart", null ],
      [ "Wait", "flow_commands.html#Wait", null ],
      [ "Wait Frames", "flow_commands.html#WaitFrames", null ],
      [ "WaitInput", "flow_commands.html#WaitInput", null ],
      [ "While", "flow_commands.html#While", null ]
    ] ],
    [ "iTween commands", "itween_commands.html", [
      [ "Look From", "itween_commands.html#LookFrom", null ],
      [ "Look To", "itween_commands.html#LookTo", null ],
      [ "Move Add", "itween_commands.html#MoveAdd", null ],
      [ "Move From", "itween_commands.html#MoveFrom", null ],
      [ "Move To", "itween_commands.html#MoveTo", null ],
      [ "Punch Position", "itween_commands.html#PunchPosition", null ],
      [ "Punch Rotation", "itween_commands.html#PunchRotation", null ],
      [ "Punch Scale", "itween_commands.html#PunchScale", null ],
      [ "Rotate Add", "itween_commands.html#RotateAdd", null ],
      [ "Rotate From", "itween_commands.html#RotateFrom", null ],
      [ "Rotate To", "itween_commands.html#RotateTo", null ],
      [ "Scale Add", "itween_commands.html#ScaleAdd", null ],
      [ "Scale From", "itween_commands.html#ScaleFrom", null ],
      [ "Scale To", "itween_commands.html#ScaleTo", null ],
      [ "Shake Position", "itween_commands.html#ShakePosition", null ],
      [ "Shake Rotation", "itween_commands.html#ShakeRotation", null ],
      [ "Shake Scale", "itween_commands.html#ShakeScale", null ],
      [ "Stop Tween", "itween_commands.html#StopTween", null ],
      [ "Stop Tweens", "itween_commands.html#StopTweens", null ]
    ] ],
    [ "LeanTween commands", "lean_tween_commands.html", [
      [ "Move", "lean_tween_commands.html#Move", null ],
      [ "Scale", "lean_tween_commands.html#Scale", null ],
      [ "Rotate", "lean_tween_commands.html#Rotate", null ]
    ] ],
    [ "Math commands", "math_commands.html", [
      [ "Abs", "math_commands.html#Abs", null ],
      [ "Clamp", "math_commands.html#Clamp", null ],
      [ "Curve", "math_commands.html#Curve", null ],
      [ "Exp", "math_commands.html#Exp", null ],
      [ "Inv", "math_commands.html#Inv", null ],
      [ "InvLerp", "math_commands.html#InvLerp", null ],
      [ "Lerp", "math_commands.html#Lerp", null ],
      [ "Log", "math_commands.html#Log", null ],
      [ "Map", "math_commands.html#Map", null ],
      [ "MinMax", "math_commands.html#MinMax", null ],
      [ "Neg", "math_commands.html#Neg", null ],
      [ "Pow", "math_commands.html#Pow", null ],
      [ "Round", "math_commands.html#Round", null ],
      [ "Sign", "math_commands.html#Sign", null ],
      [ "Sqrt", "math_commands.html#Sqrt", null ],
      [ "ToInt", "math_commands.html#ToInt", null ],
      [ "Trig", "math_commands.html#Trig", null ]
    ] ],
    [ "Narrative commands", "narrative_commands.html", [
      [ "Clear Menu", "narrative_commands.html#ClearMenu", null ],
      [ "Control Stage", "narrative_commands.html#ControlStage", null ],
      [ "Conversation", "narrative_commands.html#Conversation", null ],
      [ "Menu", "narrative_commands.html#Menu", null ],
      [ "Menu Timer", "narrative_commands.html#MenuTimer", null ],
      [ "Portrait", "narrative_commands.html#Portrait", null ],
      [ "Say", "narrative_commands.html#Say", null ],
      [ "Set Language", "narrative_commands.html#SetLanguage", null ],
      [ "Set Menu Dialog", "narrative_commands.html#SetMenuDialog", null ],
      [ "Set Say Dialog", "narrative_commands.html#SetSayDialog", null ]
    ] ],
    [ "Scripting commands", "scripting_commands.html", [
      [ "Comment", "scripting_commands.html#Comment", null ],
      [ "Call Method", "scripting_commands.html#CallMethod", null ],
      [ "Debug Log", "scripting_commands.html#DebugLog", null ],
      [ "Destroy", "scripting_commands.html#Destroy", null ],
      [ "Execute Lua", "scripting_commands.html#ExecuteLua", null ],
      [ "Invoke Event", "scripting_commands.html#InvokeEvent", null ],
      [ "Invoke Method", "scripting_commands.html#InvokeMethod", null ],
      [ "Open URL", "scripting_commands.html#OpenURL", null ],
      [ "Set Active", "scripting_commands.html#SetActive", null ],
      [ "Spawn Object", "scripting_commands.html#SpawnObject", null ]
    ] ],
    [ "Sprite commands", "sprite_commands.html", [
      [ "Fade Sprite", "sprite_commands.html#FadeSprite", null ],
      [ "Set Clickable 2D", "sprite_commands.html#SetClickable2D", null ],
      [ "Set Collider", "sprite_commands.html#SetCollider", null ],
      [ "Set Draggable 2D", "sprite_commands.html#SetDraggable2D", null ],
      [ "Set Mouse Cursor", "sprite_commands.html#SetMouseCursor", null ],
      [ "Set Sorting Layer", "sprite_commands.html#SetSortingLayer", null ],
      [ "Set Sprite Order", "sprite_commands.html#SetSpriteOrder", null ],
      [ "Show Sprite", "sprite_commands.html#ShowSprite", null ]
    ] ],
    [ "Variable commands", "variable_commands.html", [
      [ "Delete Save Key", "variable_commands.html#DeleteSaveKey", null ],
      [ "Load Variable", "variable_commands.html#LoadVariable", null ],
      [ "Random Float", "variable_commands.html#RandomFloat", null ],
      [ "Random Integer", "variable_commands.html#RandomInteger", null ],
      [ "Read Text File", "variable_commands.html#ReadTextFile", null ],
      [ "Reset", "variable_commands.html#Reset", null ],
      [ "Save Variable", "variable_commands.html#SaveVariable", null ],
      [ "Set Save Profile", "variable_commands.html#SetSaveProfile", null ],
      [ "Set Variable", "variable_commands.html#SetVariable", null ]
    ] ],
    [ "UI commands", "ui_commands.html", [
      [ "Fade UI", "ui_commands.html#FadeUI", null ],
      [ "Get Text", "ui_commands.html#GetText", null ],
      [ "Get Toggle State", "ui_commands.html#GetToggleState", null ],
      [ "Set Interactable", "ui_commands.html#SetInteractable", null ],
      [ "Set Slider Value", "ui_commands.html#SetSliderValue", null ],
      [ "Set Text", "ui_commands.html#SetText", null ],
      [ "Set Toggle State", "ui_commands.html#SetToggleState", null ],
      [ "Write", "ui_commands.html#Write", null ]
    ] ],
    [ "Tests commands", "tests_commands.html", [
      [ "Fail", "tests_commands.html#Fail", null ],
      [ "Pass", "tests_commands.html#Pass", null ],
      [ "TestNarrative", "tests_commands.html#TestNarrative", null ]
    ] ]
];